package com.synthese.enums;

public enum Errors {
    INVALID_CREDENTIALS,
    INVALID_ESTABLISHMENT,
    ESTABLISHMENT_NOT_FOUND,
    ALREADY_EXISTING_MANAGER,
    ALREADY_EXISTING_TEACHER,
    PROGRAM_NOT_FOUND,
    ALREADY_EXISTING_PROGRAM,
    ALREADY_EXISTING_COURSE,
    TEACHER_NOT_FOUND,
    NO_STUDENT_ADDED,
    STUDENTS_PARTIALLY_ADDED,
    SCHEDULE_GENERATION_FAILED, CHAT_GPT_FAILED, ALREADY_EXISTING_STUDENT
}