package com.synthese.enums;

public enum Errors {
    INVALID_CREDENTIALS,
    INVALID_ESTABLISHMENT,
    ESTABLISHMENT_NOT_FOUND,
    ALREADY_EXISTING_MANAGER, ALREADY_EXISTING_TEACHER, ALREADY_EXISTING_STUDENT
}